### ISSUE TITLE
Upgrade YAML to latest openly supported, production ready version

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#1]
YAML 0.3 has extensive usage of deprecated smart pointer syntax which causes a variety of build warnings on C++ 11 compilers/platforms.

Tasks:

1) Upgrade YAML

2) Verify that build warnings are removed

3) Ensure that test suite is clean

4) Update build instructions

5) commit

**Comment by spdomin** [comment]
Looks like: http://www.yaml.org Points to: https://github.com/jbeder/yaml-cpp/

I built the above version on my Mac - which was clean. Lots of internal changes to make in the code. Most notably the removal of FindValue... My guess is that this will be a day or two effort. @gantech, you may want to consult with @skennon10 if you get stuck.

**Comment by skennon10** [comment]
I've used both old and new versions, so please let me know if I can help.

**Comment by gantech** [comment]
Thanks. I forked Nalu here https://github.com/gantech/Nalu and will be developing this feature on a branch. @skennon10 I'll ask you questions as I go through this process. Finally I'll issue a pull-request after code-review by you guys and passing of all tests in NaluRTest.

**Comment by gantech** [comment]
I have a version that compiles with the latest yaml-cpp interface. @skennon10 it would be great if you could take a look at commit https://github.com/gantech/Nalu/commit/147ff710b4b9e51d481a7d1d1fd5e7864662dc75 and let me know if seems reasonable. I'm running tests now. I also made a small repo https://github.com/gantech/tryYAMLCPP to try out some options before implementing them in nalu.

**Comment by spdomin** [comment]
Sounds good. I tagged and released the code yesterday to make sure that we have a clean break from the 0.3.0 standard...

**Comment by gantech** [comment]
Pull request submitted. Ready to change installation instructions if pull-request is accepted.

**Comment by spdomin** [comment]
Okay, I should get to this soon...

**Comment by spdomin** [comment]
Greetings @NaluCFD/core team. Ganesh's hard work on the YAML conversion has paid off. I am performing the final tests today and expect to accept his pull request by COB tomorrow. This step will require a new YAML clone and build since the latest YAML is not backward compatible with 0.3.0. 

The new version from which we will be operating will be as follows: 

https://github.com/jbeder/yaml-cpp

If you saw, I created a v1.1.0 tag for both Rtest and Nalu. Therefore, this release will be the last code that supports 0.3.0.

Happy YAML-ing.

PS. We still have some usability issues to resolve, most notably, https://github.com/NaluCFD/NaluRtest/issues/9

**Comment by spdomin** [comment]
I found the source of the diff... inputFireEdgeUpwind has the following:

    - wall_boundary_condition: bc_pool
      target_name: surface_1
      wall_user_data:
        temperature: 298.0
        transmissivity: 0.0
        emissivity: 0.8
        temperature: 500.0

In other words, two temperature specifications..

**Comment by gantech** [comment]
There is one other issue to consider. See https://github.com/NaluCFD/NaluRtest/blob/master/nightly/ablUnstableEdge/ablUnstableEdge.i, the source_terms in solution_options is specified twice. However, they're additive in this case. I had to go back to the existing overloaded stream operators for SolutionOptions.C because they append to an existing datastructure. The new suggested method of loading complex data structures in the yaml-cpp github website would overwrite the first one with the second one.

```
137         - source_terms: 
138             momentum: buoyancy 
139             continuity: density_time_derivative 
166         - source_terms: 
167             momentum: body_force 

```

**Comment by spdomin** [comment]
But you resolved this correct with your last commit before re I accepted the pull request right?

**Comment by gantech** [comment]
Yes. The double_specification of terms in solution_options is handled the same way as the old yaml using overloaded stream operators. 

 The last commit before you accepted the pull request was to remove boost/lexical_cast includes and one other unused variable to reduce compiler warnings.

**Comment by spdomin** [comment]
Task completed.
