### ISSUE TITLE
Add proper NaluUnit repository

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#11]
Let's invert the pyramid in Nalu regression testing and start building a high quality unit test harness. The former NaluUnit was more like a sandbox.

**Comment by spdomin** [comment]
Placeholder:

https://github.com/NaluCFD/NaluUnit

**Comment by alanw0** [comment]
I'm interested in doing this. 
We should talk to make sure we're on the same or similar page, but I think unit-tests will be most useful if they are in the same repository as the code they test.
I think the gtest system makes unit-tests very easy to manage. I see that our trilinos configuration already has the gtest dependencies imported and ready to use. If you want, I can trivially show you what it would look like to put the tests in NaluUnit into gtest form.

**Comment by spdomin** [comment]
NaluUnit is operational now. 

NaluSandbox is ready for play.
