### ISSUE TITLE
get_if_present() seems off...

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#110]
A nightly test is failing due to the fact that the following line:

`get_if_present(node, "output_frequency", outputFreq_);`

returns outputFreq_ as 0 rather than what it has been specified to be in the constructor (10).

The get_if_present() method seems to be off in that it is returning a value of outputFreq_ that is based on some default if not present...

@sayerhs has a recent code commit that is failing due to a divide by zero whereas either @skennon10 or @gantech own the code base.

Interestingly, in most all of my use cases, I peform the following:

`get_if_present(y_output, "paraview_script_name", paraviewScriptName_, paraviewScriptName_);`

**Comment by gantech** [comment]
This line is present in ABLForcing.C, OutputInfo.C and DataProbePostProcessing.C. I haven't committed to any of them recently. Which nightly test?

**Comment by sayerhs** [comment]
Please see pull request #112. This was a misinterpretation at my end on how `get_if_present` works. I have fixed the usage in `src/ABLForcing.C`

**Comment by spdomin** [comment]
I still think that the method may still be confusing. As noted above, all of my usage of this method matches what your pull request now does. However, after review of the name and functionality, I wonder if there is a better API that would reduce future mistakes.

I might thing that a method named "get_if_present" would simply set the value of the parameter if it was present and do nothing if it were not present.

**Comment by sayerhs** [comment]
@spdomin I agree with your statement. `get_if_present` should not require us to send variable twice. It is clearer if `get_if_present` behaved like `get_if_present_no_default` and we had a `get_or_set_default` that did what `get_if_present` is doing.

**Comment by gantech** [comment]
Let me look into the yaml interface and figure out if there's a better way. May be we could replace all such instances of `get_if_present`. @spdomin Do you want to create another issue reg. this and assign it to me? Or we could just keep this issue until resolved.

**Comment by spdomin** [comment]
@gantech, let's keep the current ticket and simply explore whether or not get_if_present() is honest in its description. I have used it for a while without any issues, however, always passed in the parameter twice. It's been a while since I first used the method. That is why the recent experience is useful in defining whether or not the API is clear. If it is, then we can close it out..

**Comment by spdomin** [comment]
I think that we decided that this method is fine and just needs to be used carefully. Closing..
