### ISSUE TITLE
Does custom ghosting negatively affect matrix assembly?

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#119]
If we have aura, XFER or sliding mesh/overset active, custom ghosting will be active.

In the setup phase, we extract the following selector and buckets:

```
  // create a localID for all active nodes in the mesh...
  const stk::mesh::Selector s_universal = metaData.universal_part()
      & !(realm_.get_inactive_selector());

  stk::mesh::BucketVector const& buckets =
      realm_.get_buckets( stk::topology::NODE_RANK, s_universal );
```

This means that some ghosted elements/edges, which are a relic of the XFER, sliding/overset, will be included even though they are not formal candidates.

@alanw0 and @skennon10, is this true? Can we add the parts of the mesh in the active blocks to help? Would we need a separate part of all of the "non essential" ghosted entities to reduce what is provided to this setup method?

**Comment by skennon10** [comment]
Stefan,


I don't understand the issue - if you're trying to avoid custom ghosted entities in certain parts of the code, can you just select out the ghosted entities there?


  stk::mesh::Selector ghosted = (!locally_owned() & !shared());



 Maybe we can talk about it tomorrow in the parking lot.


-- Steve


________________________________

**Comment by spdomin** [comment]
Well, in cases such as overset, sliding mesh, or periodic, we actually want the contributions from ghosted entities.

What I am asking is if we have ghosted elements from, e.g., an XFER, those ghosted elements are still served up to the setupLinSys method. I guess I am asking if we think this is an issue.

Let's talk about it tomorrow.

**Comment by alanw0** [comment]
I'm not sure whether including the ghosted entities is an issue, but if you need help selecting or excluding certain entities, I can help. Each 'ghosting' has an associated part, so we could select or exclude entities from any particular ghosting and not others, assuming that a different ghosting is used for xfer vs overset, etc.

**Comment by spdomin** [comment]
Yes, I think (at the very least) that it may be useful to exclude XFER. In the sliding mesh scheme, I think that we already prune candidate elements that did not turn out to be required in the core algorithm. The same methodology would need to be deployed for overset and periodic. If we did that, then these algorithms would always have a custom ghosting list that was "true".
