### ISSUE TITLE
Support for pyramid elements on an exposed boundary

### ISSUE THREAD

**Issue by mbarone81** [NaluCFD/Nalu#127]
Nalu does not currently support pyramid elements on an exposed boundary.  The master element code does not define exposed face integration point node maps, for example.  This causes a runtime error when a boundary condition algorithm requests these maps.  @spdomin and I discussed defining the boundary ip node map for pyramids, thereby allowing a pyramid to sit on a symmetry boundary.  However, the momentum symmetry bc algorithm computes dndx at the boundary, requiring a face_grad_op, which is also currently undefined for pyramids.

**Comment by spdomin** [comment]
Yes, feel free to add ipNodeMap and face_grad_op. This will allow all flux BCs to work WITH EXCEPTION of the DG scheme. If you want that working, we will need to implement the general_face_grad_op and mappings between side IPs and volume IPs.

**Comment by mbarone81** [comment]
@spdomin I do not see shifted exposed face points defined for any of the elements in MasterElement.C.  I see intgLoc_ and intgLocShift_ for internal element ip's.  I see intgExpFace_ but no intgExpFaceShift_.

**Comment by mbarone81** [comment]
Looks like I have the code working for a duct with pyramids at all 6 boundaries, with inflow, open, symmetry, and wall all exercised.
![ductpyr](https://cloud.githubusercontent.com/assets/6090175/26214562/0eaf1da0-3bba-11e7-9866-1baedb1b0bd2.png)

**Comment by spdomin** [comment]
Looks good. We need to ask the Trilinos team for an STK update. Also, I can get you that 2x1 verification test.

**Comment by mbarone81** [comment]
I have created a pull request addressing this issue so I am closing it.

**Comment by spdomin** [comment]
We have a new use case in which pyramids are required at DG interfaces.

@rcknaus, @mbarone81 or @spdomin, let's negotiate:) Anyone working today or tomorrow has first dibs as I would like to launch my full-up tower simulation very soon.
