### ISSUE TITLE
Normal distance to the wall usage for resolved and wall function simulation

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#13]
When computing y+, what is the value of Yp that should be used?

The current wall-resolved implementation is using a normal distance = 1/4*normalOpposingEdgeDistance. However, based on the usage of the projected nodal gradient, this distance should simply be normalOpposingEdgeDistance.

For the wall-function approach, more thought is required.

**Comment by spdomin** [comment]
Wall-resolved case improved: commit 16e309a82244a5c626303c195e48847de5766c67

Higher order may add complexity - or not...

**Comment by spdomin** [comment]
@mbarone81, while you are working on the ABL, think about the wall-modeled approach and the appropriate normal distance to use. I am thinking that it is also the full edge-length.

**Comment by mbarone81** [comment]
Will do -- my first thoughts are that full edge length is appropriate.

**Comment by spdomin** [comment]
Recent LOW findings suggest that the projected approach is the most ideal implementation when using wall functions. 

At present, the resolved YPlus calculation is based on the full edge-length and the Yplus for standard wall functions is 1/4 edge distance.
