### ISSUE TITLE
SuperLU_4.3 compilation on Certainty (Stanford)

### ISSUE THREAD

**Issue by lluisjofre** [NaluCFD/Nalu#136]
When building SuperLU_4.3 on Certainty (Stanford), in addition to copying the src files to the install directory, I had to also copy the lib files:  cp lib/* $nalu_build_dir/install/SuperLU_4.3/lib

All the other builds went perfectly. Thanks for the detailed instructions.

Lluis

**Comment by spdomin** [comment]
Great to hear. The plan is to deprecate SuperLU usage. We are waiting on @jhux2 to resolve some strange behavior when we moved in this direction.
