### ISSUE TITLE
Deploy full Pyramid5 support - 

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#138]
We have a new use case in which pyramids are required at DG interfaces. 

We also need to implement isInElement() for a pyramid for XFERS

@rcknaus, @mbarone81 or @spdomin, let's negotiate:) Anyone working today or tomorrow has first dibs as I would like to launch my full-up tower simulation very soon.

Here is the list:

For DG:

```
meSCSCurrent->sidePcoords_to_elemPcoords(currentFaceOrdinal, 1, &currentIsoParCoords[0],    &currentElementIsoParCoords[0]);

meSCSCurrent->general_face_grad_op(currentFaceOrdinal, &currentElementIsoParCoords[0], &p_c_elem_coordinates[0], &p_c_dndx[0], &ws_c_det_j[0], &scs_error);
```

For XFER:

```
      const double nearestDistance = meSCS->isInElement(&theElementCoords[0],
                                                        &(tocoords[0]),
                                                        &(isoParCoords[0]));

```
I would also like to take the opportunity to check our sidePcoords_to_elemPcoords() implementations. We could do this by the following:

1) at the current gauss point, determine the boundary integration point coordinates.
2) call isInElement on the opposing element. Compute the coordinates of this gauss point using the general interpolatePoint method on the opposing face.
3) call isInElement on the opposing face and compare the isoparametric coordinates from the isInElement call and the sidePcoords.

**Comment by mbarone81** [comment]
I will tackle general_face_grad_op.

**Comment by rcknaus** [comment]
I'll take isInElement and interpolatePoint.

**Comment by spdomin** [comment]
Let's fix this kind of stuff everywhere: **REMOVE ME**

```
//--------------------------------------------------------------------------
//-------- general_face_grad_op --------------------------------------------
//--------------------------------------------------------------------------
void 
Tri2DSCS::general_face_grad_op(
  const int /*face_ordinal*/,
  const double */*isoParCoord*/,
  const double *coords,
  double *gradop,
  double *det_j,
  double *error)
{
  int lerr = 0;
  
  const int nface = 1;
  double dpsi[6];
  **double grad[6];**
  
  // derivatives are constant
  SIERRA_FORTRAN(tri_derivative)
    ( &nface, dpsi );
      
  SIERRA_FORTRAN(tri_gradient_operator)
    ( &nface,
      &nodesPerElement_,
      &nface,
      dpsi,
      &coords[0], grad, &det_j[0], error, &lerr );
      
  if ( lerr )
    std::cout << "sorry, issue with face_grad_op.." << std::endl;
  
  **for ( int j=0; j<6; j++) {
    gradop[j] = grad[j];
  }**
}
```

**Comment by spdomin** [comment]
I will take sidePcoords...

**Comment by spdomin** [comment]
Just a note... 

Neither meCurrentSCS->isInElement() nor meOpposingSCS->isInElement() can be called using the current face Gauss point integration coordinates to determine the current and opposing isoParametric coordinates and used with the general_face_grad_op(). This is due to the fact that the underlying general_face_grad_op calls through to the, e.g., hex_derivatives() which is based on a -1/2 : 1/2 range. Therefore, we need to "correct" the currentIsoParametric coordinates, which were based on a -1:1 range via this sidePcoords method. However, these new corrected points must only be used for dndx calcs - nothing more, e.g, meCurrentSCS->general_shape_fcn().

**Comment by spdomin** [comment]
here is my first take on sideP mapping.. I need to check the ip ordering for the faces.

```
//--------------------------------------------------------------------------
//-------- sidePcoords_to_elemPcoords --------------------------------------
//--------------------------------------------------------------------------
void 
PyrSCS::sidePcoords_to_elemPcoords(
  const int & side_ordinal,
  const int & npoints,
  const double *side_pcoords,
  double *elem_pcoords)
{
  switch (side_ordinal) {
  case 0:
    for (int i=0; i<npoints; i++) {//face0: tri3
      elem_pcoords[i*3+0] = side_pcoords[2*i+0]);
      elem_pcoords[i*3+1] = -1.0;
      elem_pcoords[i*3+2] = side_pcoords[2*i+1];
    }
    break;
  case 1:
    for (int i=0; i<npoints; i++) {//face1: tri3
      elem_pcoords[i*3+0] = 1.0;
      elem_pcoords[i*3+1] = side_pcoords[2*i+0];
      elem_pcoords[i*3+2] = side_pcoords[2*i+1];
    }
    break;
  case 2:
    for (int i=0; i<npoints; i++) {//face2: tri3
      elem_pcoords[i*3+0] = side_pcoords[2*i+0];
      elem_pcoords[i*3+1] = 1.0;
      elem_pcoords[i*3+2] = side_pcoords[2*i+1];
    }
    break;
  case 3:
    for (int i=0; i<npoints; i++) {//face3: tri3
      elem_pcoords[i*3+0] = -1.0;
      elem_pcoords[i*3+1] = side_pcoords[2*i+0];
      elem_pcoords[i*3+2] = side_pcoords[2*i+1];
    }
    break;
  case 4:
    for (int i=0; i<npoints; i++) {//face3: quad4
      elem_pcoords[i*3+0] = side_pcoords[2*i+0];
      elem_pcoords[i*3+1] = side_pcoords[2*i+1];
      elem_pcoords[i*3+2] = 0.0;
    }
    break;
  default:
    throw std::runtime_error("PyrSCS::sidePcoords_to_elemPcoords invalid ordinal");
  }
}
```

**Comment by mbarone81** [comment]
Unless I missed something, the pyramid general_face_grad_op method is trivial:

//--------------------------------------------------------------------------
//-------- general_face_grad_op --------------------------------------------
//--------------------------------------------------------------------------
void 
PyrSCS::general_face_grad_op(
  const int face_ordinal,
  const double *isoParCoord,
  const double *coords,
  double *gradop,
  double *det_j,
  double *error)
{
  int lerr = 0;
  const int nface = 1;

  double dpsi[15];

  SIERRA_FORTRAN(pyr_derivative)
    ( &nface, &isoParCoord[0], dpsi );
      
  SIERRA_FORTRAN(pyr_gradient_operator)
    ( &nface,
      &nodesPerElement_,
      &nface,
      dpsi,
      &coords[0], gradop, &det_j[0], error, &lerr );
  
  if ( lerr )
    std::cout << "PyrSCS::general_face_grad_op: issue.." << std::endl;
  
}

**Comment by spdomin** [comment]
Yes, it is trivial:) Did you clean up all of those grad copies?

**Comment by spdomin** [comment]
Okay, STK has been updated and the Pyr5SCS unit test is now failing due to an inconsistency between the Nalu master elements and stk_topo. I have a Trilinos update processing now along with a patch to the PyrSCS elements that I will push ASAP.

@NaluCFD/core - this means you will need to update T past SHA1:

Trilinos/develop SHA1: 9541173a4752545b6c96ba172f368a70144cfc67

**Comment by spdomin** [comment]
Looking good... I have a temp implementation for general_face_grad_op() in my local branch (will wait on formal push by @mbarone81 )

Below is a tet/pyr DG flow with pyr at the middle of the domain. Using consolidated algs with NSO.

![tetpyrdg_one](https://cloud.githubusercontent.com/assets/8699324/26498915/f229e8b0-41ed-11e7-9dc4-e0e5aca5dbc6.png)
![tetpyrdg_two](https://cloud.githubusercontent.com/assets/8699324/26498916/f3aa1bf6-41ed-11e7-8992-9bf3ab9e36dd.png)
![tetpyrdg_three](https://cloud.githubusercontent.com/assets/8699324/26498918/f5ab5d34-41ed-11e7-8a79-44890820303c.png)

**Comment by spdomin** [comment]
Verified and now closing.
