### ISSUE TITLE
Could you please introduce how to generate Nalu mesh file ?

### ISSUE THREAD

**Issue by wwzb3** [NaluCFD/Nalu#165]
Only a few .g files or .e files in binary format.  How to generate these mesh file with popular mesh generator such as ICEMCFD ?

**Comment by sayerhs** [comment]
Nalu's binary mesh files are in [Exodus II](http://prod.sandia.gov/techlib/access-control.cgi/1992/922137.pdf) format. You can export to this format from several popular mesh generation software.

**Comment by spdomin** [comment]
ICEMCFD supports Exodus II - as does Pointwise and Cubit.

For viz, we generally use Ensight, Paraview or Visit (the later of the two are open-source)..

**Comment by spdomin** [comment]
Are there any more questions on this ticket such that we can close it?

**Comment by spdomin** [comment]
Closing ticket.
