### ISSUE TITLE
Two `tkeProdLimitRatio` questions

### ISSUE THREAD

**Issue by marchdf** [NaluCFD/Nalu#166]
I was wondering about a couple things as I was digging through some source code. 

1. Why is `tkeProdLimitRatio` different for SST (set to 10, as described in Menter2003 model) and for SST-DES (set to 500)? 
2. Why is `tkeProdLimitRatio` in the sdr source term not set to `TM_tkeProdLimitRatio` as it is in other files? I would think the following change is necessary: 
```
--- a/src/SpecificDissipationRateSSTNodeSourceSuppAlg.C
+++ b/src/SpecificDissipationRateSSTNodeSourceSuppAlg.C
@@ -46,7 +46,7 @@ SpecificDissipationRateSSTNodeSourceSuppAlg::SpecificDissipationRateSSTNodeSourc
     dkdx_(NULL),
     dwdx_(NULL),
     dualNodalVolume_(NULL),
-    tkeProdLimitRatio_(10.0),
+    tkeProdLimitRatio_(realm.get_turb_model_constant(TM_tkeProdLimitRatio)),
```

**Comment by spdomin** [comment]
I agree that we should allow for a user to specify this ratio limit and have the code respect it in all cases. As such, your code change above is appropriate.

As for proper default values, 10 and 500 seem arbitrary to me. In most cases, in nature, turbulent flows never see a value greater than O(100). However, 10 seems too small. However, from what I found a long time ago in other codes, 10 was used. If you have other default values that you find more useful, feel free to make this change.

**Comment by marchdf** [comment]
@spdomin. Thanks for confirming. Btw that code change will cause a diff in `elemBackStepLRSST` reg test since it uses `sst_des` and `tkeProdLimitRatio` is set to 500 but ignored and set to 10 in the SDR equation. This change will make the SDR equation use the user specified value.  I will put in a pull request for this change.

10 is the value used in the literature for the SST model (at least Menter2003 onward). I don't know what should be used for SST-DES but I wanted to check the rational of 500 before messing with things.
