### ISSUE TITLE
reg_tests/CMakeLists.txt backwards compatibility with cmake

### ISSUE THREAD

**Issue by mbarone81** [NaluCFD/Nalu#168]
When running the Nalu configure script, cmake v2.8.12.2 complains about the following in reg_tests/CMakeLists.txt : 

  Syntax error in cmake code at
    /ascldap/users/mbarone/CODES/Nalu_ActuatorLine/reg_tests/CMakeLists.txt:10
  when parsing string
    Testing is enabled, but the mesh submodule is not initialized.\
   You should 'git submodule init' and 'git submodule update'\
   before running the tests.

  syntax error, unexpected cal_SYMBOL, expecting $end (124)

If I use a more recent version of cmake (3.4.3), this error goes away; however, then cmake is incompatible with the rest of my development environment so then I get compile errors.

**Comment by spdomin** [comment]
I thought that we needed CMAKE 3.1 at least for any and all Nalu builds?

**Comment by sayerhs** [comment]
@spdomin No currently Nalu is set for 2.8.11

```
cmake_minimum_required (VERSION 2.8.11)
```

**Comment by mbarone81** [comment]
module 'sierra-devel/intel-16.0-openmpi-1.8' on skybridge loads git 2.6.1, leading to my problem.

**Comment by spdomin** [comment]
We should change the build documentation as I originally captured a 3.1 requirement. I think that may have been the superset of all platforms and known make bugs.

@mbarone81, send me the issue you saw on Sky and we can go from there.
