### ISSUE TITLE
Clash over equation names in TpetraLinSys

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#183]
When TpetraLinSys extracts the equation system, it uses the name that what is provided in the constructor. However, this name can end up being the user supplied name and not the one that was used to create the Eqs. This is due to the fact that the parser reads in the user supplied name afterwards.

The consequence of this is that in some cases, eqSys_ is null in TpetraLinSys. Therefore, the re-init is not working correctly for equation systems that allow the user name supplied to persist. These are single equations, e.g., enthalpy, species, mixture fraction. Equations that are wrapped in a larger equation system, e.g., LowMachEQS, which include momentum and continuity are fine.

May cause diffs?

The fix here is to: 1) add a notion of "userSuppliedName_" and 2) just provide Tpetra the EquationSystem at construction since it holds a pointer to it anyway (why retrieve it later when we have it at construction - especially when it is a data member of LinSys.

@spdomin to take care of this issue..

**Comment by alanw0** [comment]
I think I like option 2 at this point. If there's confusion about different names referring to a given equation system, that should probably be cleaned up too, but it's not even an issue for TpetraLinearSystem if we go with option 2 and just give it the EquationSystem at construction. We were probably thinking about unit-testability previously, which I still think is important, but the confusion of names is not a reasonable trade-off.

**Comment by alanw0** [comment]
I'll go ahead and do this unless you are doing it.

**Comment by spdomin** [comment]
No, I have complete... I am also merging this pull request with the other nonlinear iteration normalization.

I found this issue only since I was trying to extract a "firstTimeSolve" data member on EQS...

Thanks for the help and comments... Look for the pull request in about 20 minutes.

**Comment by spdomin** [comment]
The following commit addressed this issue:

https://github.com/NaluCFD/Nalu/commit/f3ede1bb528dae6eb0f66f08ee797a08e71bbe02
