### ISSUE TITLE
Segfault in Dirichlet BC in debug

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#191]
@NaluCFD/core, I have a number of production runs failing in Debug with the following error at the applyDirichlet() step. This seems to be a periodic/Dirichlet clash, however, I can not be certain.

Throw number = 1
Throw test that evaluated to true: true
Teuchos::ArrayView<int const> : You can not call operator->() or operator*() if getRawPtr()==0!

I replicated this case on an eight-core job using the ablUnstableEdge test.

However, for the above case, I needed to change:
       use_abl_wall_function: yes
to:
       use_abl_wall_function: no

in order to exercise the Dirichlet bc. I am not sure if we have other periodic/Dirichlet Rtests?

**Comment by spdomin** [comment]
I bisected to @alanw0 : https://github.com/NaluCFD/Nalu/commit/2ee2b3702ba75cadf355980304e3d36b89a38364

I plan on reverting and we can tackle this with a clean-running debug code base; running tests now.

**Comment by alanw0** [comment]
I'm pretty sure I know exactly what the issue is with this, it should be a quick fix. But this is where I really wish I could unit-test tpetralinearsystem...

**Comment by spdomin** [comment]
Agreed... Let's take this up when the improved unit test story is pulled. Thanks for the quick response and resolution of the issue.
