### ISSUE TITLE
Deprecate usage of Epetra solver interface

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#2]
Epetra represents the 32-bit limited Trilinos solver stack. 

Tpetra represents the 64-bit compliant Trilinos solver stack.

Activities:
1.  Remove instances of Epetra usage in favor of a single Trilinos interface
2. Retain the polymorphic solver interface design to allow future solver prototyping
3. Modify regression test to transition to Tpetra/Balos/ifpack2/Muelu.

**Comment by alanw0** [comment]
I'd be happy to help with this activity.

**Comment by spdomin** [comment]
@alanw0 thanks for the offer. Let's have @jhux2 or @srajama1 take this on since it ties to a long ago Trilinos bugzilla ticket that spoke to the fact that the new solver stack is far more sensitive on remote platforms than Epetra/Aztec.

**Comment by srajama1** [comment]
This will depend on Trilinos issue https://github.com/trilinos/Trilinos/issues/649

I am working tech-X to remove this dependence. @jhux2 can take over once that issue is closed.

**Comment by spdomin** [comment]
Who can actually do this task? Now that I am re-writing the Tpetra sumInto infrastrcture, this is getting hard to manage.

Can someone do this task this week? If not, I will be forced to take it over or assign it to someone else.

**Comment by spdomin** [comment]
I am doing this today.

**Comment by spdomin** [comment]
@jhux2  and/or @srajama1 I hit a snag in a conversion test:

Throw number = 13

Throw test that evaluated to true: rowMap->getComm()->getSize() > 1

MueLu::Amesos2Smoother::Setup Fixing coarse matrix for Amesos2 for multiple processors has not been implemented yet.

**Comment by jhux2** [comment]
@spdomin Is MueLu building a one-level multigrid method, i.e., is Amesos2 being called directly on the Nalu PPE linear system?

**Comment by jhux2** [comment]
See discussion in Trilinos issue [889](https://github.com/trilinos/Trilinos/issues/889).

**Comment by jhux2** [comment]
@spdomin I was under the impression that the tests in NaluRtest were run with both Epetra and Tpetra, but this must not be the case.  Are there some tests that were Epetra only before you started the conversion?

**Comment by spdomin** [comment]
@jhux2 For legacy purposes, we included Epetra-based solves for bench marking against the new Tpetra solver stack. Now that I am removing Epetra, it is time to transition the old tests to use the new solver stack.

**Comment by spdomin** [comment]
@NaluCFD/core, Epetra usage is now deprecated. As such, the last code base that uses Epetra (and, for the record, YAML 0.3.0) is the v1.1.0-release.

Make sure that you update Nalu and NaluRtest for a clean running set of tests.

**Comment by spdomin** [comment]
I am opening this back up until we can have a clean Trilinos configure without including the Epetra solver stack.

**Comment by spdomin** [comment]
Builds of Trilinos are now free of Epetra stack.
