### ISSUE TITLE
Use of undeclared variable in ComputeWallModelSDRAlgorithm.C

### ISSUE THREAD

**Issue by gantech** [NaluCFD/Nalu#200]
I get the following error message when compiling Nalu in debug mode:

```
src/ComputeWallModelSDRWallAlgorithm.C:113:38: error: 'nodesPerFace' was not declared in this scope
       ThrowAssert( num_face_nodes == nodesPerFace );
```

 I checked and there's no variable declared as nodesPerFace.

**Comment by alanw0** [comment]
You might need to pull, the current version of the code contains no such ThrowAssert.

**Comment by gantech** [comment]
Yup... I see that now. @rcknaus had specifically addressed it in a commit.
