### ISSUE TITLE
Incorrect version of NaluMesh pointed to in the Nalu repo

### ISSUE THREAD

**Issue by sayerhs** [NaluCFD/Nalu#212]
Currently the NaluMesh submodule points to NaluCFD/NaluMesh@3b681ed whereas the `HEAD` points to NaluCFD/NaluMesh@2a71277. The submodule is missing the actuator line meshes/files necessary to run OpenFAST tests. Related to #93 

Cc: @jrood-nrel

**Comment by jrood-nrel** [comment]
Thanks Shreyas. Also, @gantech I'm wondering if `libDISCON_glin64.so` should be removed? It looks like a library.

Side note: maybe we should have called that repo NaluData.

**Comment by sayerhs** [comment]
@jrood-nrel that is the controller library... I suspect that will fail on OSX, so probably should need to replace with a build directive.

**Comment by jrood-nrel** [comment]
Hmm, why wouldn't OpenFAST build that itself?

**Comment by sayerhs** [comment]
Controller files are not part of FAST, they are usually created using Matlab Simulink or otherwise and loaded during runtime to turbine simulation codes. For most OEM turbines, these files will be blackbox libraries that we don't have source code access too. NREL 5MW controller code resides with the NREL 5MW geometry files...

**Comment by sayerhs** [comment]
With the merge of #214 this issue has been fixed with a newer version of `NaluMesh`
