### ISSUE TITLE
bytes_per_thread fix...

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#215]
bytes_per_thread = 3simdLen;

//3 is wrong, still need to debug this!!! should be 2 but seems to have memory problems.

**Comment by alanw0** [comment]
Yes. I change the '3' to '2' (which is what I think it should be) and all nightly tests pass.
I think next I'll do a valgrind run to make sure it's ok. It could be an issue that was solved during development a while back...

**Comment by alanw0** [comment]
ok, I've pushed the change that sets the allocation multiplier to 2. I confirmed all nightly tests are still passing, and also verified that there are no memory errors in the elemHybridFluids test.
