### ISSUE TITLE
get_scs_shape_fn_data() used in FEM-based kernel

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#218]
Looks like the FEM-based scalar kernel uses: get_scs_shape_fn_data(). However, this method requires that numScsIps_ and nodesPerElem_ are used.

**Comment by alanw0** [comment]
Might be necessary to add a "get_fem_shape_fn_data()".

**Comment by spdomin** [comment]
Yes... See my pull request...

**Comment by spdomin** [comment]
Code pushed to resolve this.
