### ISSUE TITLE
VLA array used in Tri32DCVFEM.C

### ISSUE THREAD

**Issue by sayerhs** [NaluCFD/Nalu#220]
```
Nalu/src/master_element/Tri32DCVFEM.C:465:19: warning:
      variable length arrays are a C99 feature [-Wvla-extension]
  DoubleType det_j[nint];
                  ^
1 warning generated.
```

**Comment by overfelt** [comment]
Shreyas, 

I pushed a one line fix for this warning but did not get an email about the push even though my project is now up to date with master.  Did the push fail or am I just not receiving emails?

**Comment by sayerhs** [comment]
@overfelt It appears that you pushed it to your [local fork](https://github.com/overfelt/Nalu/commit/54ca538853c1886f2ad650fc5248c8525a9e3f6f) and not to NaluCFD/Nalu repo.

**Comment by overfelt** [comment]
Drat.
