### ISSUE TITLE
STK::SIMD Header Files are Not Found in Trilinos Develop

### ISSUE THREAD

**Issue by nmhamster** [NaluCFD/Nalu#228]
I expect you already know about this but using Trillinos `develop` branch with NALU-CFD results in:

```
[  1%] Building CXX object CMakeFiles/nalu.dir/src/ActuatorLinePointDrag.C.o
In file included from /ascldap/users/sdhammo/git/nalucfd-github-repo/include/master_element/MasterElement.h(17),
                 from /ascldap/users/sdhammo/git/nalucfd-github-repo/src/ActuatorLinePointDrag.C(17):
/ascldap/users/sdhammo/git/nalucfd-github-repo/include/SimdInterface.h(18): catastrophic error: cannot open source file "stk_simd/Simd.hpp"
  #include "stk_simd/Simd.hpp"
```

I can manually fix this up but just wanted to put this on your radar.

**Comment by jrood-nrel** [comment]
Hmm. Nalu just ran last night without errors using:
```
*** Base Git Repo: Trilinos
b8ed76f [Sun Oct 22 15:45:12 2017 -0600] <mhoemme@sandia.gov>
Merge branch 'develop' of github.com:trilinos/Trilinos into develop
```

**Comment by sayerhs** [comment]
@nmhamster Can you check if the Trilinos@develop was compiled using `-DTrilinos_ENABLE_STKSimd:BOOL=ON \` flag?

**Comment by nmhamster** [comment]
@sayerhs / @jrood-nrel - I am just checking that, you guys read my mind. I have so many automated tests for Trilinos and NALU I have probably missed. Will report back shortly.

**Comment by nmhamster** [comment]
@sayerhs / @jrood-nrel - thanks, I hadn't updated that particular script to include STK::SIMD. All fixed now. Thanks!
