### ISSUE TITLE
Missing Area Magnitude in ABL Wall Function

### ISSUE THREAD

**Issue by mchurchf** [NaluCFD/Nalu#230]
I think there is an error in the ABL wall function in that the stress is never multiplied by face area before entering the LHS.  If you look at the standard wall function AssembleMomentumEdgeWallFunctionSolverAlgoirthm.C lines 197-199, you see:

        double lambda = muBip/yp*aMag;
        if ( yplus > yplusCrit_)
          lambda = rhoBip*kappa_*utau/std::log(elog_*yplus)*aMag;

lambda includes the face area magnitude.

Then, if you go to AssembleMomentumEdgeABLWallFunctionSolverAlgorithm.C line 246, you see:

        double lambda = rhoBip*kappa_*utau/(std::log(yp/z0_) - p_ABLProfFun->velocity(yp/L));

Here aMag is not included.  I think it should be:

        double lambda = (rhoBip*kappa_*utau/(std::log(yp/z0_) - p_ABLProfFun->velocity(yp/L))) * aMag);

**Comment by sayerhs** [comment]
I would like to add that this error is also present in the Element based algorithm `AssembleMomentumElemABLWallFunctionSolverAlgorithm.C`

**Comment by mbarone81** [comment]
I agree that this is an error.  I will push a fix.

**Comment by spdomin** [comment]
Yesterday, I launched an ABL case for both edge- and element-based with this aMag fix. Both schemes are predicting nearly the same velocity components while the velocity magnitude dropped from ~6 m/s to ~4 m/s.

It will be good to have this cleaned up ASAP. We should check with other Nalu users to see if ABL has been used in production mode.

Finally, we may want to patch the previously tagged v1.1.

**Comment by spdomin** [comment]
As a matter of practice for future issues, please link (either hard-coded or mentioned) the commit/pull request prior to closing any issue. We want the traceability between code commit and issue to be clear.

https://github.com/NaluCFD/Nalu/pull/232
