### ISSUE TITLE
NALU_ALIGN hard codes to 64 bit alignment

### ISSUE THREAD

**Issue by sayerhs** [NaluCFD/Nalu#231]
The `#define` of `NALU_ALIGN` ignores the size parameter passed. -- [KokkosInterface.h](https://github.com/NaluCFD/Nalu/blob/master/include/KokkosInterface.h#L15)

```
#define NALU_ALIGN(size) __attribute__((aligned(64)))
```

**Comment by alanw0** [comment]
Good catch, that's a silly bug. I'll fix it right now.

**Comment by alanw0** [comment]
ok I just pushed a fix for this.
