### ISSUE TITLE
CDash conversion to HTTPS

### ISSUE THREAD

**Issue by jrood-nrel** [NaluCFD/Nalu#291]
I got a reply to my email to Kitware about the CDash website not posting successfully submitted test results. This was apparently due to a problem where they recently converted the site to HTTPS and it caused some projects appear blank. They seem to have solved that problem for us.

This obviously coincides with the certificate issue Sandia is seeing so I'm creating this issue and we can see if the certificate problem persists and I can continue to follow up with Kitware regarding it.

**Comment by jrood-nrel** [comment]
@spdomin @rcknaus Has Sandia still been experiencing issues with this HTTPS change to CDash?

**Comment by jrood-nrel** [comment]
I emailed Kitware about the certificate errors Sandia is seeing.

**Comment by spdomin** [comment]
I think that we can close this. Kitware offered a solution that our lab was neither willing nor able to deploy.
