### ISSUE TITLE
NALU Does Not Detect YAML-CPP Since Recent Change

### ISSUE THREAD

**Issue by nmhamster** [NaluCFD/Nalu#309]
Something seems to have changed in the `CMakeLists.txt` which is causing YAML-CPP to not get detected properly.

```
############################ YAML ######################################
60 set(CMAKE_PREFIX_PATH ${YAML_DIR} ${CMAKE_PREFIX_PATH})
61 find_package(YAML-CPP REQUIRED)
62 if(YAML-CPP_FOUND)
63 message("-- Found YAML-CPP = ${YAML_DIR}")
64 endif()
65 include_directories(${YAML_CPP_INCLUDE_DIR})
```

The result is that CMake configuration time fails with:

```
CMake Error at CMakeLists.txt:61 (find_package):
  By not providing "FindYAML-CPP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "YAML-CPP",
  but CMake did not find one.

  Could not find a package configuration file provided by "YAML-CPP" with any
  of the following names:

    YAML-CPPConfig.cmake
    yaml-cpp-config.cmake

  Add the installation prefix of "YAML-CPP" to CMAKE_PREFIX_PATH or set
  "YAML-CPP_DIR" to a directory containing one of the above files.  If
  "YAML-CPP" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
```

**Comment by jrood-nrel** [comment]
Ah, this is my fault. I apologize. Since the `yaml-cpp` project has not tagged a new version in a quite a long time, many of us have been using the `develop` branch of `yaml-cpp` which provides `yaml-cpp-config.cmake` and fixes many warnings when building Nalu. I forgot to check backwards compatibility with version 0.5.3 (which we suggest in the build instructions) which I just verified does not provide `yaml-cpp-config.cmake`. A quick solution here will be to build `yaml-cpp` from its `develop` branch. I will work to find a proper resolution to this issue.

**Comment by spdomin** [comment]
Si, can this be closed now? Please let us know if you still are noting any issues.

**Comment by nmhamster** [comment]
@spdomin - I cloned master again today and am still having problems.

**Comment by spdomin** [comment]
Sorry to hear that. Let's try to resolve this ASAP.

By master, do you mean master yaml?

Perhaps @jrood-nrel can also advise. In my Mac build, I needed to re-clone YAML from github. This allowed me to work past the YAML errors. However, at the same time, my latest code base in Nalu with the old clone from YAML is working. This probably means I missed some subtlety that Jon can help us through.

**Comment by jrood-nrel** [comment]
Since any new errors are not described, I'm assuming you are still seeing the original errors? I tried the latest YAML-CPP master and the latest Nalu master this morning and I am unable to reproduce any issues. I am using CMake 3.6.1 and 3.9.4 typically, but other than that, I'm not sure what else to suggest at the moment.

**Comment by nmhamster** [comment]
@jrood-nrel / @spdomin - same errors as before. I am using YAML 0.5.3 on our systems and then hacking the `CMakeLists.txt` file so it works with that install.

**Comment by jrood-nrel** [comment]
Try replacing the YAML section with this:

**Comment by jrood-nrel** [comment]
Linking to a pull request I made addressing this in Spack for posterity.  https://github.com/spack/spack/pull/7245

**Comment by nmhamster** [comment]
@jrood-nrel - updated this morning to build on Sky Lake and I'm still seeing this error. Just wanted to keep you in the loop.

```
CMake Error at CMakeLists.txt:63 (find_package):
  By not providing "FindYAML-CPP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "YAML-CPP",
  but CMake did not find one.

  Could not find a package configuration file provided by "YAML-CPP" with any
  of the following names:

    YAML-CPPConfig.cmake
    yaml-cpp-config.cmake

  Add the installation prefix of "YAML-CPP" to CMAKE_PREFIX_PATH or set
  "YAML-CPP_DIR" to a directory containing one of the above files.  If
  "YAML-CPP" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
```

**Comment by jrood-nrel** [comment]
@nmhamster So you have updated to the yaml-cpp master branch and this still isn't working? Please try `rm -rf CMakeCache.txt CMakeFiles/` in the build directory before configuring and see if that helps.

**Comment by jrood-nrel** [comment]
#345 Resolved this. @sayerhs and I worked with @nmhamster over a call and verified it worked.
