### ISSUE TITLE
Selector definition in AssembleElemSolverAlgorithm should exclude inactive_selector

### ISSUE THREAD

**Issue by sayerhs** [NaluCFD/Nalu#340]
I would expect the [AssembleElemSolverAlgorithm](https://github.com/NaluCFD/Nalu/blob/master/include/AssembleElemSolverAlgorithm.h#L62) to use a selector similar to the non-consolidated ElemSolverAlgorithms. However, it does not seem to exclude `realm_.get_inactive_selector()` and I suspect will create issues when running overset cases with consolidated algorithms. Is this a bug or is there a particular reason why this is coded this way? 

I think Line 62-63 should be modified to:

```
   stk::mesh::Selector s_locally_owned_union =
           meta_data.locally_owned_part() 
         & stk::mesh::selectUnion(partVec_)
         & !(realm_.get_inactive_selector();
```

Cc: @alanw0, @spdomin

**Comment by spdomin** [comment]
Right, this is a WIP and needs to add the inactive part. FaceElem looks clean as we do not support inactive parts at bcs. Any one can crank this out with the above proposed fix.

**Comment by alanw0** [comment]
I agree, the inactive selector should be added to the selector in AssembleElemSolverAlgorithm. I'll do that unless one of you already did.

**Comment by alanw0** [comment]
ok, it's pushed.
