### ISSUE TITLE
NALU Compile Error with GCC 7.2.0

### ISSUE THREAD

**Issue by nmhamster** [NaluCFD/Nalu#341]
I am trying to compile NALU-CFD on POWER8 systems with GCC 7.2.0. The version is from today. Just wanted to let you know what has come up.

```
/ascldap/users/sdhammo/git/nalucfd-github-repo/src/PecletFunction.C:113:16: error: duplicate explicit instantiation of ‘class sierra::nalu::ClassicPecletFunction<double>’ [-fpermissive]
 template class ClassicPecletFunction<DoubleType>;
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/ascldap/users/sdhammo/git/nalucfd-github-repo/src/PecletFunction.C:114:16: error: duplicate explicit instantiation of ‘class sierra::nalu::TanhFunction<double>’ [-fpermissive]
 template class TanhFunction<DoubleType>;
                ^~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/nalu.dir/src/PecletFunction.C.o] Error 1
make[2]: Leaving directory `/home/sdhammo/git/nalucfd-github-repo/build-gcc-720'
make[1]: *** [CMakeFiles/nalu.dir/all] Error 2
make[1]: Leaving directory `/home/sdhammo/git/nalucfd-github-repo/build-gcc-720'
make: *** [all] Error 2
```

**Comment by sayerhs** [comment]
@nmhamster Thanks for the heads up. Can you confirm that you are not using the `-DTrilinos_ENABLE_STKSimd:BOOL=ON` option when compiling Trilinos?

**Comment by sayerhs** [comment]
@nmhamster I added a fix to Nalu that should allow you to compile Nalu without enabling STK SIMD in Trilinos. Can you please give this latest commit a try and let me know if you are able to compile it? Thanks.

**Comment by nmhamster** [comment]
@sayerhs - I **do** have `-D Trilinos_ENABLE_STKSimd:BOOL=ON` in my Trilinos configure.

**Comment by sayerhs** [comment]
@nmhamster Sorry my mistake, I overlooked the fact that the code didn't complain about including `stk_simd/Simd.hpp`. 

The fix I committed should fix your compilation issue of duplicate explicit instantiation.

**Comment by nmhamster** [comment]
Testing under way ... (@sayerhs - thanks for putting the fix in quickly!)

**Comment by nmhamster** [comment]
@sayerhs - I think we got past this code but I am getting loads of linking errors with TPetra. Argh. Need to go back and take a look at what's happening here. :-(

**Comment by spdomin** [comment]
I think that this issue was resolved. If not, we can re-open.
