### ISSUE TITLE
Changes in either Trilinos or Nalu are causing 13 tests to fail with the Intel compiler

### ISSUE THREAD

**Issue by jrood-nrel** [NaluCFD/Nalu#358]
Today 13 more tests are failing due most likely to changes in Trilinos, but there was also 40 files updated in Nalu from #356 and #352 .

The errors are as such:
```
Belos::StatusTestImpResNorm::checkStatus(): One or more of the current implicit residual norms is NaN.
terminate called after throwing an instance of 'Belos::StatusTestError'
  what():  ......../intel-17.0.2/trilinos-develop-fx2gnncdv4lrtv72rymaqf5cjn3ng7s2/include/BelosStatusTestImpResNorm.hpp:635:
```

**Comment by spdomin** [comment]
@jrood-nrel, #356 was a localized change to affect only the Element-based wall function approach that is touched in only one test. #352 was larger, however, also should only be localized to a small number of tests. 

Sorry that I missed this before we just processed a few pull requests. Nans are bad enough to halt the development process until we sort through the errors.

@rcknaus, can you bisect Nalu to ensure that the changes we recently used did not cause the nans?

**Comment by rcknaus** [comment]
#352 is the culprit.  The issue is a weird one, though: changes in a declaration of a Kokkos::View in face_grad_op will cause grad_op to fail.  I'm looking at it a bit with address sanitizer to see if there's a memory error somewhere

**Comment by spdomin** [comment]
@rcknaus, if you can revert while you sort this out, that might be useful.

**Comment by jrood-nrel** [comment]
Since these changes were reverted, I'm going to close this issue and make a new issue if anything shows up in the tests again.
