### ISSUE TITLE
Data probes not working with epetra solvers

### ISSUE THREAD

**Issue by msv5450** [NaluCFD/Nalu#403]
I wanted to output some data probe files so I added a data_probes section to the input file according to the Nalu user Manual. The problem is that Nalu is able to read the probe point specifications, but the job gets terminated upon "EquationSystems::initialize(): Begin". Afterwards, it gives this run time error: "Throwing an instance of INT", followed by other error messages about failure to initialize different things. One of these initialization errors is about "Epetra" solver. 

I recently found out that this thing doesn't happen when I DO NOT use any solvers of type "epetra". So, when I switch to "tpetra" solvers for all the equations, the code works fine and the probe data files are generated. 

Could you explain why probe points are not compatible with "epetra" solvers? Is there a way to remedy this?

By the way, I am using Trilinos 12.4.0 and Nalu 1.1.0. Could this be an issue with the version of my Trilinos?

**Comment by spdomin** [comment]
Epetra was deprecated just after the 1.1 release. I would move to Tpetra.

As for the proper Trilinos version for 1.1, let me check and report back.

**Comment by spdomin** [comment]
v11 seems to be the version of Trilinos.
