### ISSUE TITLE
Mixed Tet/Hex mesh

### ISSUE THREAD

**Issue by msv5450** [NaluCFD/Nalu#408]
Is NALU able to handle a mesh that is composed of both tet and hex elements. I made a mesh that is half tet and half hex. I see some numerical errors, like spurious heat generation, at the interface of hex and tet regions where the tet/hex node are connected to each other. This is a conformal mesh by the way and tet and hex regions are separate blocks. 

If NALU can numerically support such a grid, is there a special treatment that I should do at the tet/hex interface in Trelis?

**Comment by spdomin** [comment]
Although a Hex8 and Tet4 mesh can be conformal, the dual volume is not well posed. As such, you either require a Pyramid5 transition layer or the usage of the non-conformal approach that would allow for a hybrid CVFEM/DG approach at the mixed interface. If your nodes of the mesh are unique to each Hex8 and Tet4 block, you may already have this option given your mesh.

**Comment by spdomin** [comment]
Closing.
