### ISSUE TITLE
buoyancy source term for turbulence models

### ISSUE THREAD

**Issue by msv5450** [NaluCFD/Nalu#426]
Why isn't a buoyancy source term defined for the transport equation of Specific Dissipation Rate in the SST RANS model, while there is such a source term in the Rodi form for the turbulent kinetic energy equation?

I've seen buoyancy source terms for both K and Omega equations in the literature.

**Comment by spdomin** [comment]
Yes, it looks like the Rodi term was only coded completely for a Ksgs approach. For two-equation RANS systems, an additional source term is required.

Feel free to issue  a pull request. Otherwise, I will put the task on the list.

**Comment by spdomin** [comment]
Added enhancement attribute as Nalu mostly focusses on LES-based approaches. However, since we support SST, we should probably be consistent. All that needs to be done is to add a Rodi source term. As we are managing edge/element and element_consolidated, some choices need to be made.

**Comment by spdomin** [comment]
Yes, good catch. I will make that bug fix now and commit.

**Comment by spdomin** [comment]
Okay, Ksgs is fixed in node-based and consolidated approaches:

https://github.com/NaluCFD/Nalu/commit/a7f96046d6b5879f2be79007ce96f343a20b3e98

and 

https://github.com/NaluCFD/Nalu/commit/1beb246683d84f579ea38e1fa6973ee5ec100151

I am closing this and adding a new bug for SST alone.
