### ISSUE TITLE
Effective viscosity in Ksgs transport equation

### ISSUE THREAD

**Issue by msv5450** [NaluCFD/Nalu#427]
I think the effective viscosity is not correctly evaluated in the code for "Subgrid-Scale Kinetic Energy One-Equation LES Model". It is correct for SST though.

According to the Ksgs governing equation:  "effective viscosity = turb_viscosity / sigma_k" and it has been assumed that  sigma_k=1.0. However, effective viscosity gets computed as the sum of molecular and turbulent viscosities in the code because the default values of "lamSc" and "turbSc" are set to 1.0 in SolutionOptions.C. Look at:

TurbKineticEnergyEquationSystem() -> EffectiveDiffFluxCoeffAlgorithm()

**Comment by spdomin** [comment]
In general, the derivation for a turbulent kinetic equation will not facilitate a laminar contribution to the effective viscosity. However, classically, it is included to add stability in the laminar regions of the flow. Feel free to set the parameter such that only the turbulent contribution is included.

**Comment by spdomin** [comment]
Here is a reference to Launder where the molecular contribution is included:

https://www.tandfonline.com/doi/pdf/10.1080/19942060.2013.11015467

For turbulent flows, adding a molecular contribution will be small while in laminar sections of the flow, adding it would enhance stability.

**Comment by spdomin** [comment]
Answered.
