### ISSUE TITLE
ECP 5(b): Evaluate dropping Jacobian entries for sliding/overset

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#43]
Remove LHS contributions for column entries on sliding mesh matrix entries that change over the simulation.

This will require modification of non-conformal algorithms in addition to increasing iterations over the continuity equation, e.g.,

```
const int numContSubIter = 10;
for ( int k = 0; k < numContSubIter; ++k ) {
    // continuity assemble, load_complete and solve
    continuityEqSys_->assemble_and_solve(continuityEqSys_->pTmp_);

    // update pressure
    timeA = NaluEnv::self().nalu_time();
    field_axpby(
      realm_.meta_data(),
      realm_.bulk_data(),
      1.0, *continuityEqSys_->pTmp_,
      1.0, *continuityEqSys_->pressure_,
      realm_.get_activate_aura());
    timeB = NaluEnv::self().nalu_time();
    continuityEqSys_->timerAssemble_ += (timeB-timeA);
}
```

Any takers from @NaluCFD/sliding or @NaluCFD/solver ?

I will start this next week if there are no volunteers.

**Comment by aprokop** [comment]
@spdomin Could you please elaborate on the ticket? I'd like to work on it but need more context.

**Comment by spdomin** [comment]
We should probably talk at the next stand-up then. The basic sliding mesh includes column entries of the opposing element for the DG contribution. If we remove those entries, the matrix structure does not change. However, this will come at the expense of more continuity iterations as noted above. I would go to the AssembleContinuityNonConformal algorithm and modify the connected nodes keeping only the current element connectivity and removing the opposing element connectivity from the stencil. You will also need to modify the Tpetra setup. Then, in the algorithm apply, you can remove the LHS += for the opposing nodes. Try one of the dg tests (possibly even removing the spinning of the block, i.e., omega = 0) and see what happens.

You can also avoid all of the above and see if there is an opportunity to "reuse" the preconditioner for Muelu.

**Comment by spdomin** [comment]
Attached are some preliminary overset and sliding mesh work when dropping Jacobian (LHS sensitivities)
[slidingOversetMeshStencil.pdf](https://github.com/NaluCFD/Nalu/files/699687/slidingOversetMeshStencil.pdf)
.

**Comment by spdomin** [comment]
Transition to Jira.
