### ISSUE TITLE
Does Nalu support a cylindrical coordinate system?

### ISSUE THREAD

**Issue by grahamg3** [NaluCFD/Nalu#489]
I can't find anything in the docs, but I was wondering if it might like some other Sierra applications.  If so, how would I specify it in the input file?

**Comment by spdomin** [comment]
Sorry, no. Nalu does not support cylindrical coordinate systems. In general, not that complex to add - especially for edge-based.

Sadly, at present, we do not have any current projects driving such development.

Let me know how you would like to proceed.

**Comment by grahamg3** [comment]
Okay thanks, that answers my question.
