### ISSUE TITLE
Is it possible to generate random perturbations in the inflow for LES simulation?

### ISSUE THREAD

**Issue by grahamg3** [NaluCFD/Nalu#491]
I am working on a simulation using the WALE model and I was trying to figure out if there is any way to introduce some kind of randomness at the inflow boundary condition to make the flow exhibit more turbulent behavior.  Is there any built in way to accomplish this that I am missing (e.g. inline functions)?  If I understand the code correctly, creating a new aux function appears to be out of the question, since I am working with the code already installed on the HPC.

**Comment by spdomin** [comment]
Yes, you would need to create a new inflow user function and make sure that any randomness of the inflow BC user function implementation provides to the AuxFunction:

`const bool parallelCommunicate = true
`

This insures the there is parallel consistency as the random approach may not take care to ensure this consistency.

We have thought about plugins that do not require a new build, however, that brings in new dynamic linking nuances.

What HPC platform are you using?

**Comment by grahamg3** [comment]
I use the Chama and Skybridge clusters.  What would it involve to create and implement a new user function?

**Comment by spdomin** [comment]
It's rather easy. Let's take this offline... Please write me at my SNL address. However, I will leave this open until we have closure.

**Comment by grahamg3** [comment]
I've successfully implemented a user function that generates enough controlled perturbations to induce turbulence (in addition to a different user function I made for a rotating wall).  It appears to be working in the simulations I have run, so for now my questions are answered and I think I can close this issue.
My functions can be found in my fork of Nalu.
