### ISSUE TITLE
ECP 2: Stand-up code repository and software build system and test harness

### ISSUE THREAD

**Issue by jrood-nrel** [NaluCFD/Nalu#50]
Activities:

  1. Create draft software design document, including code requirements around building, testing, and documentation. 
  2. Establish a public-facing code repository.
  3. Choose and implement build system and testing harness on dedicated testing cluster for nightly building and testing.

**Comment by jrood-nrel** [comment]
So I think this will be mostly my responsibility going forward on the NREL side. For number 1 I'm not sure what we already have, but I can work to consolidate it. For number 2, I think I'm looking right at it, so that one is done. For number 3, we know I am working to automate the build as much as I can with Spack, and Marc has already implemented CDash that we will expand upon.

To expand upon where I'm at with number 3, I am satisfied with the build automation on NREL's Peregrine machine, and now I'm working on generalizing the Trilinos package file in Spack enough to where I can get Nalu to build on top of it without having to use my customized Trilinos package file. Then hopefully I can get a Nalu package file into the official Spack repo for more general use.

I will continue to update this.

**Comment by spdomin** [comment]
Move to Jira.
