### ISSUE TITLE
Outlet Boundary Reflections

### ISSUE THREAD

**Issue by dstevensperegrine** [NaluCFD/Nalu#505]
I am running a WALE model of turbulent flow in a pipe. The model is displaying significant backflow and reflection at the outlet boundary. Does NALU support any type of non-reflecting or damping options at outlet boundaries?

Thank you,

David Stevens
Staff Engineer
Peregrine Turbine Technologies

**Comment by spdomin** [comment]
David,

We have a standard "open" bc with or without a total pressure option. 

Something sounds off in your simulation as I have run pipes, channels, jets, basically most all low-Mach configurations, with success. If you can post or email your input file to me, that would help.

Best,

**Comment by dstevensperegrine** [comment]
Stefan,

I have attached the input file. You will notice the inlet uses a velocity profile interpolation function that what written Sal Rodriguez and Graham Monroe at SNL. Note the file also contains proprietary data so please do not post it on git.

I currently have a 0 pressure outlet condition.

I noticed you mentioned “total pressure”. Are all the pressures input and output in Nalu at stagnation conditions?

Thank you,

David

David W. Stevens | Staff Engineer
Peregrine Turbine Technologies, LLC
29 South Point Drive  |  Wiscasset, ME  04578
Office: (207) 687-8333
Cell:    (207) 776-2996
dstevens@peregrineturbine.com<mailto:dstevens@peregrineturbine.com>  |  www.peregrineturbine.com<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.peregrineturbine.com%2f&c=E,1,gUtrbt3MdNtiRcuYQRYw_zhbtDKXMMDOQQNsIPLq0elz85sj-x4yCdv-q6tXbSUilyHsPYcEiLMq0_w42S49dOsB-ETMsSPIqBg8Qt26_C2IRKMsDj_m&typo=1>

[4B68C7BA]
This e-mail message including any attachments is for the sole use of the intended recipient(s) and may contain privileged or confidential information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please immediately contact the sender by reply e-mail and delete the original message and destroy all copies thereof. The sender does not accept liability for any errors or omissions.

**Comment by spdomin** [comment]
Any update on this? Otherwise, I may choose to close with your permission.

**Comment by dstevensperegrine** [comment]
Stefan,

Sorry I had to put this on the back burner for a bit. I think I found a work around but would mind having you look at my input file if you dont mind. Can I send to you email?

Thank you for your assistance,

David

**Comment by spdomin** [comment]
Please do.

**Comment by dstevensperegrine** [comment]
Stefan,

I have attached my Nalu input file.

Thank you,

David

David W. Stevens | Staff Engineer
Peregrine Turbine Technologies, LLC
29 South Point Drive  |  Wiscasset, ME  04578
Office: (207) 687-8333
Cell:    (207) 776-2996
dstevens@peregrineturbine.com<mailto:dstevens@peregrineturbine.com>  |  www.peregrineturbine.com<https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.peregrineturbine.com%2f&c=E,1,gUtrbt3MdNtiRcuYQRYw_zhbtDKXMMDOQQNsIPLq0elz85sj-x4yCdv-q6tXbSUilyHsPYcEiLMq0_w42S49dOsB-ETMsSPIqBg8Qt26_C2IRKMsDj_m&typo=1>

[4B68C7BA]
This e-mail message including any attachments is for the sole use of the intended recipient(s) and may contain privileged or confidential information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please immediately contact the sender by reply e-mail and delete the original message and destroy all copies thereof. The sender does not accept liability for any errors or omissions.

**Comment by spdomin** [comment]
Let's take this user support to internal email. Please email me at my work account and send the input, mesh, and XML file. Best,
