### ISSUE TITLE
The error of compilation with tioga

### ISSUE THREAD

**Issue by ShenglinYan** [NaluCFD/Nalu#506]
When I compiled the NaluCFD with tioga, come across an error. The fellowing is  the error information:

/home/cfd/Nalu/packages/Nalu/src/overset/TiogaBlock.C: In member function ‘void tioga_nalu::TiogaBlock::get_donor_info(tioga&, stk::mesh::EntityProcVec&)’:
/home/cfd/Nalu/packages/Nalu/src/overset/TiogaBlock.C:214:3: error: invalid use of incomplete type ‘class tioga’
   tg.getDonorCount(meshtag_, &dcount, &fcount);
   ^~
In file included from /home/cfd/Nalu/packages/Nalu/src/overset/TiogaBlock.C:10:0:
/home/cfd/Nalu/packages/Nalu/include/overset/TiogaBlock.h:16:7: note: forward declaration of ‘class tioga’
 class tioga;
       ^~~~~
/home/cfd/Nalu/packages/Nalu/src/overset/TiogaBlock.C:226:3: error: invalid use of incomplete type ‘class tioga’
   tg.getDonorInfo(meshtag_,receptorInfo.data(),inode.data(),
   ^~
In file included from /home/cfd/Nalu/packages/Nalu/src/overset/TiogaBlock.C:10:0:
/home/cfd/Nalu/packages/Nalu/include/overset/TiogaBlock.h:16:7: note: forward declaration of ‘class tioga’
 class tioga;
       ^~~~~
/home/cfd/Nalu/packages/Nalu/src/overset/TiogaBlock.C: In member function ‘void tioga_nalu::TiogaBlock::register_block(tioga&)’:
/home/cfd/Nalu/packages/Nalu/src/overset/TiogaBlock.C:459:3: error: invalid use of incomplete type ‘class tioga’
   tg.registerGridData(
   ^~
In file included from /home/cfd/Nalu/packages/Nalu/src/overset/TiogaBlock.C:10:0:
/home/cfd/Nalu/packages/Nalu/include/overset/TiogaBlock.h:16:7: note: forward declaration of ‘class tioga’
 class tioga;
       ^~~~~
/home/cfd/Nalu/packages/Nalu/src/overset/TiogaBlock.C:475:3: error: invalid use of incomplete type ‘class tioga’
   tg.set_cell_iblank(meshtag_, iblank_cell_.data());
   ^~
In file included from /home/cfd/Nalu/packages/Nalu/src/overset/TiogaBlock.C:10:0:
/home/cfd/Nalu/packages/Nalu/include/overset/TiogaBlock.h:16:7: note: forward declaration of ‘class tioga’
 class tioga;
       ^~~~~
CMakeFiles/nalu.dir/build.make:6254: recipe for target 'CMakeFiles/nalu.dir/src/overset/TiogaBlock.C.o' failed
make[2]: *** [CMakeFiles/nalu.dir/src/overset/TiogaBlock.C.o] Error 1
CMakeFiles/Makefile2:424: recipe for target 'CMakeFiles/nalu.dir/all' failed
make[1]: *** [CMakeFiles/nalu.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Thank you!

**Comment by spdomin** [comment]
Greetings, The Nalu code base does not formally support Tioga. If you are interested in overset, I suggest that you either attempt using our simplistic STK-based hole cutting or move towards the Nalu-wind product: https://github.com/exawind.

I can remove Tioga from the code base to make this more clear. Let me know if I there is anything else.

**Comment by spdomin** [comment]
Had this been resolved? I am closing for now and will be happy to re-open should we still have a problem.
