### ISSUE TITLE
OpenSSL requirement while building manually

### ISSUE THREAD

**Issue by mulligatawny** [NaluCFD/Nalu#526]
Cmake requires OpenSSL to configure. Is it OK to build without it? The 

`./configure --prefix=$nalu_install_dir/cmake/3.12.3/ -- -DCMAKE_USE_OPENSSL=OFF`

option allows this, but I am not sure if OpenSSL is needed by any of the other packages.

**Comment by spdomin** [comment]
Yes, my understanding is that this is expected to be OFF.
