### ISSUE TITLE
Mac build warning

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#541]
@wjhorne, I just noticed the build warning below on the Mac platform. This may be hard to test for you since you may not have access to a Mac (check with dev-ops), however, the change should be simple enough to resolve.

/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:3709:5: warning: destructor called on non-final 'sierra::nalu::OrientedCylinder'
      that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
    __data_.second().~_Tp();
    ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:3670:9: note: in instantiation of member function
      'std::__1::__shared_ptr_emplace<sierra::nalu::OrientedCylinder, std::__1::allocator<sierra::nalu::OrientedCylinder> >::__on_zero_shared' requested
      here
        __shared_ptr_emplace(_Alloc __a, _Args&& ...__args)
        ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:4330:26: note: in instantiation of function template specialization
      'std::__1::__shared_ptr_emplace<sierra::nalu::OrientedCylinder, std::__1::allocator<sierra::nalu::OrientedCylinder>
      >::__shared_ptr_emplace<std::__1::pair<stk::search::Box<double>, stk::search::IdentProc<unsigned long long, int> > &, std::__1::vector<double,
      std::__1::allocator<double> > &, std::__1::vector<double, std::__1::allocator<double> > &, std::__1::vector<double, std::__1::allocator<double> >
      &, int &>' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:4709:29: note: in instantiation of function template specialization
      'std::__1::shared_ptr<sierra::nalu::OrientedCylinder>::make_shared<std::__1::pair<stk::search::Box<double>, stk::search::IdentProc<unsigned long
      long, int> > &, std::__1::vector<double, std::__1::allocator<double> > &, std::__1::vector<double, std::__1::allocator<double> > &,
      std::__1::vector<double, std::__1::allocator<double> > &, int &>' requested here
    return shared_ptr<_Tp>::make_shared(_VSTD::forward<_Args>(__args)...);
                            ^
/Users/naluIt/gitHubWork/nightlyBuildAndTest/Nalu/src/overset/OversetManagerSTK.C:704:22: note: in instantiation of function template specialization
      'std::__1::make_shared<sierra::nalu::OrientedCylinder, std::__1::pair<stk::search::Box<double>, stk::search::IdentProc<unsigned long long, int> >
      &, std::__1::vector<double, std::__1::allocator<double> > &, std::__1::vector<double, std::__1::allocator<double> > &, std::__1::vector<double,
      std::__1::allocator<double> > &, int &>' requested here
    fineShape = std::make_shared<OrientedCylinder>(boundingModelBoxVec[0],
                     ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:3709:23: note: qualify call to silence this warning
    __data_.second().~_Tp();
                      ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:3709:5: warning: destructor called on non-final 'sierra::nalu::OrientedBox' that
      has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
    __data_.second().~_Tp();
    ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:3670:9: note: in instantiation of member function
      'std::__1::__shared_ptr_emplace<sierra::nalu::OrientedBox, std::__1::allocator<sierra::nalu::OrientedBox> >::__on_zero_shared' requested here
        __shared_ptr_emplace(_Alloc __a, _Args&& ...__args)
        ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:4330:26: note: in instantiation of function template specialization
      'std::__1::__shared_ptr_emplace<sierra::nalu::OrientedBox, std::__1::allocator<sierra::nalu::OrientedBox>
      >::__shared_ptr_emplace<std::__1::pair<stk::search::Box<double>, stk::search::IdentProc<unsigned long long, int> > &, std::__1::vector<double,
      std::__1::allocator<double> > &, std::__1::vector<double, std::__1::allocator<double> > &, std::__1::vector<double, std::__1::allocator<double> >
      &>' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:4709:29: note: in instantiation of function template specialization
      'std::__1::shared_ptr<sierra::nalu::OrientedBox>::make_shared<std::__1::pair<stk::search::Box<double>, stk::search::IdentProc<unsigned long long,
      int> > &, std::__1::vector<double, std::__1::allocator<double> > &, std::__1::vector<double, std::__1::allocator<double> > &,
      std::__1::vector<double, std::__1::allocator<double> > &>' requested here
    return shared_ptr<_Tp>::make_shared(_VSTD::forward<_Args>(__args)...);
                            ^
/Users/naluIt/gitHubWork/nightlyBuildAndTest/Nalu/src/overset/OversetManagerSTK.C:708:22: note: in instantiation of function template specialization
      'std::__1::make_shared<sierra::nalu::OrientedBox, std::__1::pair<stk::search::Box<double>, stk::search::IdentProc<unsigned long long, int> > &,
      std::__1::vector<double, std::__1::allocator<double> > &, std::__1::vector<double, std::__1::allocator<double> > &, std::__1::vector<double,
      std::__1::allocator<double> > &>' requested here
    fineShape = std::make_shared<OrientedBox>(boundingModelBoxVec[0],
                     ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:3709:23: note: qualify call to silence this warning
    __data_.second().~_Tp();

**Comment by wjhorne** [comment]
Just implemented the fix that should address this and will shoot a merge request of it after a little bit of testing.

**Comment by spdomin** [comment]
Great. if you issue a pull request, I can test it on my Mac system.

**Comment by wjhorne** [comment]
PR has been submitted for this issue. I was able to reproduce the original warning using Clang on Linux without issue.
