### ISSUE TITLE
ECP 3: Demonstrate single blade-resolved simulation in non-rotating turbulent inflow

### ISSUE THREAD

**Issue by gantech** [NaluCFD/Nalu#55]

**Comment by gantech** [comment]
I've been working on this from the later half of December 2016. I have had discussions with Scott Schreck at NREL to choose the validation dataset. He recommended the NREL-VI experiments, specifically the parked rotor dataset. I have been able to get a CAD model from him and build a grid around it. Will send a detailed write up of all the info I have on it along with a plan to reach the milestone for comments and discussion before the stand up tomorrow.

**Comment by spdomin** [comment]
Transition to Jira.
