### ISSUE TITLE
Questions about building Nalu under Ubuntu

### ISSUE THREAD

**Issue by 2000zyy** [NaluCFD/Nalu#554]
I tried to build Nalu semi-Automatically using spack under Ubuntu.But when I execute the fourth step, the terminal displays "Machine name not found." as shown in the figure below.How to solve this problem?
![捕获](https://user-images.githubusercontent.com/87939588/134016963-d3ca3268-4ab3-416e-84d6-bb1d51b04a2f.JPG)

**Comment by spdomin** [comment]
Closing. Let us know if this is still something that is not working.
