### ISSUE TITLE
1.5.2 build issue

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#582]
During Trilinos config using a variety of intel gcc mpi options:

CMake Error at /shared/nalu/install/cmake/3.17.0/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/opt/intel/oneapi/mpi/2021.1.1/bin/mpicc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /shared/nalu/build/packages/Trilinos/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/gmake cmTC_6a003/fast && /usr/bin/gmake -f CMakeFiles/cmTC_6a003.dir/build.make CMakeFiles/cmTC_6a003.dir/build
    gmake[1]: Entering directory `/shared/nalu/build/packages/Trilinos/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_6a003.dir/testCCompiler.c.o
    /opt/intel/oneapi/mpi/2021.1.1/bin/mpicc    -o CMakeFiles/cmTC_6a003.dir/testCCompiler.c.o   -c /shared/nalu/build/packages/Trilinos/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_6a003
    /shared/nalu/install/cmake/3.17.0/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6a003.dir/link.txt --verbose=1
    /opt/intel/oneapi/mpi/2021.1.1/bin/mpicc      CMakeFiles/cmTC_6a003.dir/testCCompiler.c.o  -o cmTC_6a003
    /usr/bin/ld: cannot find -lmpifort
    /usr/bin/ld: cannot find -lmpi
    collect2: error: ld returned 1 exit status
    gmake[1]: *** [cmTC_6a003] Error 1
    gmake[1]: Leaving directory `/shared/nalu/build/packages/Trilinos/build/CMakeFiles/CMakeTmp'
    gmake: *** [cmTC_6a003/fast] Error 2

@mulligatawny or @bartlettroscoe, any ideas? I plan on digging into this tomorrow.

**Comment by bartlettroscoe** [comment]
@spdomin, looks like an issue with the MPI compiler wrapper?  You should look in the CMakeFiles/ directory for more information.

**Comment by jrood-nrel** [comment]
@spdomin I would be curious if these might succeed for Intel OneAPI:
```
-DCMAKE_CXX_COMPILER=mpiicpx \
-DCMAKE_C_COMPILER=mpiicx \
-DCMAKE_Fortran_COMPILER=mpiifx \
```

**Comment by spdomin** [comment]
> @spdomin I would be curious if these might succeed for Intel OneAPI:
> 
> ```
> -DCMAKE_CXX_COMPILER=mpiicpx \
> -DCMAKE_C_COMPILER=mpiicx \
> -DCMAKE_Fortran_COMPILER=mpiifx \
> ```

Thank you. We will try this path today and report back. 

Best,

**Comment by spdomin** [comment]
Okay, this is resolved. We had some config file mistakes and all has been resolved. Thank you for tuning in and offering support, @bartlettroscoe and @jrood-nrel !
