### ISSUE TITLE
Portions of Non-conformal boundaries that do not overlap

### ISSUE THREAD

**Issue by mhamadAlloush** [NaluCFD/Nalu#586]
Hi,

Does the non-conformal boundary treatment in the code assume that the two boundaries should always be overlapping? What if I have one large boundary interfacing with another smaller one? How is the non overlapping boundary treated here?

Regards and Many Thanks!

**Comment by spdomin** [comment]
Greetings,

The non-conformal algorithm (see the JCP manuscript, https://doi.org/10.1016/j.jcp.2018.01.007 ) assumes that 1) the two surfaces are close, i.e., no gaps, and 2)the surfaces are of similar geometric fidelity, i.e,, consider a curved section with faceting from low-order meshes.

We have not formalized the behavior when there are disparate mesh resolutions on either boundary. In our paper above, we ran mesh disparities of roughly a factor of two. Ideally, those are close as well.

best,

**Comment by spdomin** [comment]
Closing. If you have further questions, let us know.
