### ISSUE TITLE
Mac build issue (Trilinos STK)

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#590]
@alanw0, I am bringing back a Mac platform and noticed the errors in Trilinos/STK below... Not sure if there is a new config option that I am missing, or something legit on the Mac clang platform. This has been down for O(12) weeks, so no real ability to bisect.

Many thank in advance for any guidance.

/Trilinos/packages/stk/stk_util/stk_util/parallel/CouplingVersions.cpp:31:28: error: implicit
      instantiation of undefined template 'std::__1::array<int, 3>'
  std::array<int, bufSize> inbuf{localVersion, localVersion, -1}, outbuf;
                           ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;

**Comment by sayerhs** [comment]
@spdomin can you try adding the following in that CPP file?

```c++
#include <array>
```

It is likely that the header was implicitly included in another header on other compilers but not in Apple clang.

**Comment by spdomin** [comment]
@sayerhs, yes thank you, this resolved the issue.

@alanw0, could you please modify:

packages/stk/stk_util/stk_util/parallel/CMakeFiles/stk_util_parallel.dir/CouplingVersions.cpp

via:
```

diff --git a/packages/stk/stk_util/stk_util/parallel/CouplingVersions.cpp b/packages/stk/stk_util/stk_util/parallel/CouplingVersions.cpp
index ea82e6c..d327887 100644
--- a/packages/stk/stk_util/stk_util/parallel/CouplingVersions.cpp
+++ b/packages/stk/stk_util/stk_util/parallel/CouplingVersions.cpp
@@ -7,6 +7,7 @@
 #include <string>
 #include <iostream>
 #include <cassert>
+#include <array>
 
 namespace stk {
 namespace util {
```


If you like, I can create a Trilinos ticket?

**Comment by spdomin** [comment]
Resolved.
