### ISSUE TITLE
ECP 4(a) ScratchView interface change

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#64]
#4 

A few notes on the templated SuppAlgs and ScratchView interface:

1. code does not build in debug (somewhat related):

 ```
from /UnitTestKokkosViews.C:5:
/Trilinos_stable_release/include/stk_mesh/baseImpl/FieldBaseImpl.hpp:152:7: warning: â*((void*)& f +40)â may be used uninitialized in this function [-Wmaybe-uninitialized]
```
       m_field_states[i] = field_states[i];

2. We also gather tensor quantities, e.g., duidxj via the following interface

```
      for ( int ni = 0; ni < num_nodes; ++ni ) {
        stk::mesh::Entity node = node_rels[ni];
        const double * du     =  stk::mesh::field_data(*dudx_, node);
        // row for p_dudx
        const int row_p_dudx = niNdim*nDim;
        for ( int i=0; i < nDim; ++i ) {
          // gather tensor
          const int row_dudx = i*nDim;
          for ( int j=0; j < nDim; ++j ) {
            p_dudx[row_p_dudx+row_dudx+j] = du[row_dudx+j];
          }
        }
      }
```
3. Let's avoid a call signature to fill_prereq_data including meSCS, meSCV, meFEM and later meFC, etc., by calls that add the master element, e.g., add_cvfem_interior_scs(), etc.

4. Remove excessive logic for each template argument to the SuppAlgs in, e.g., HeatCondEQs::register_interior()

5. @alanw0, I think that coordField can also be removed since it is part of the "add" infrastructure...
```
  fill_pre_req_data(dataNeededBySuppAlgs_, bulk_data, topo, meSCS, meSCV, element,
                        coordField, prereqData);

```

6. This call can be elevated in ElemSolver from inner bucket loops since topo is fixed for the ElemSolver:

```
stk::mesh::Bucket & b = *elem_buckets[team.league_rank()];
    stk::topology topo = b.topology();
    sierra::nalu::MasterElement* meSCS = realm_.get_surface_master_element(topo);
    sierra::nalu::MasterElement* meSCV = realm_.get_volume_master_element(topo);

```
6. Possibly more...

**Comment by alanw0** [comment]
@spdomin what other details can you give me about the "may be used uninitialized" compile warning above? i.e., What compiler and/or stk version is producing this? I know you sent an email to the stk team about this recently but I don't think anyone was able to reproduce it.

**Comment by spdomin** [comment]
I added the detail to the formal ticket now under our internal management. All I can think is the -Wall through out the entire code build? I think our internal system allows for dialing in such options between the code and TPL. However, if you look at the code, it looks uninitialized (possibly) regardless of whether or not there is a compile warning.

**Comment by spdomin** [comment]
This may also be bad for hybrid mesh sims:

```
  for(const stk::mesh::FieldBase* fieldPtr : neededFields) {
     stk::mesh::EntityRank fieldEntityRank = fieldPtr->entity_rank();
     ThrowAssertMsg(fieldEntityRank == stk::topology::NODE_RANK || fieldEntityRank == stk::topology::ELEM_RANK, "Currently only node and element fields are supported.");
     unsigned scalarsPerEntity = fieldPtr->max_size(fieldEntityRank);
     numBytes += scalarsPerEntity*sizeof(double);
   }
```

**Comment by spdomin** [comment]
Transition to Jira.
