### ISSUE TITLE
ECP 10: Memory reduction techniques for higher-order

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#7]
Activities:
1. Establish static condensation approaches with local, fast solves.
2. Deploy preconditioner coarsening strategies which may require only the P=1 system to be stored.
3. Evaluate matrix-free methods for both advection/diffusion and possible PPE.

**Comment by srajama1** [comment]
Is there some some pointers for reading one can start with ? What is the local, fast solve here, LU on small blocks ?

**Comment by spdomin** [comment]
@srajama1 take a look at the attached reference for the basics of the higher order method:

https://web.stanford.edu/group/ctr/Summer/SP14/09_Large-eddy_simulation/03_domino.pdf

Also, please interface with @rcknaus as he has some good papers on static condensation and local solves.

**Comment by spdomin** [comment]
Transition to Jira.
