### ISSUE TITLE
Linear system imbalance in ABL strong-scaling simulations

### ISSUE THREAD

**Issue by jhux2** [NaluCFD/Nalu#73]
@spdomin @alanw0 @aprokop @mbarone81 
In looking at the ABL strong scaling simulations on 256, 512, and 1024 cores, we have observed that the linear system passed into MueLu becomes more imbalanced as the core count grows.  (See data below).  This will very likely affect communication in the preconditioner setup.

I have some initial questions:

- How is the distribution of the fine grid matrix determined?  Is it primarily from the decomposition of the underlying grid?
- Are there options available in the Nalu input deck that can change/influence the matrix distribution?

### 256 cores
```
A0 size =  2113536 x 2113536, nnz = 15155200
A0 Load balancing info
A0   # active processes: 256/256
A0   # rows per proc   : avg = 8.26e+03,  dev =   3.4%,  min =   -7.0%,  max =   +8.7%
A0   #  nnz per proc   : avg = 5.92e+04,  dev =   5.1%,  min =   -9.2%,  max =  +13.5%
A0 Communication info
A0   # num export send : avg =     0.00,  dev =   0.00,  min =    0.0 ,  max =    0.0
A0   # num import send : avg = 2.51e+03,  dev =   5.6%,  min =  -11.0%,  max =  +10.6%
A0   # num msgs        : avg =     9.50,  dev =   1.39,  min =    6.0 ,  max =   13.0
A0   # min msg size    : avg = 2.56e+00,  dev = 157.3%,  min =  -61.0%,  max = +485.4%
A0   # max msg size    : avg = 5.20e+02,  dev =   2.5%,  min =   -1.5%,  max =   +7.9%
```

### 512 cores
```
A0 size =  2113536 x 2113536, nnz = 15155200
A0 Load balancing info
A0   # active processes: 512/512
A0   # rows per proc   : avg = 4.13e+03,  dev =   3.7%,  min =   -7.0%,  max =  +12.0%
A0   #  nnz per proc   : avg = 2.96e+04,  dev =   7.3%,  min =   -9.2%,  max =  +24.1%
A0 Communication info
A0   # num export send : avg =     0.00,  dev =   0.00,  min =    0.0 ,  max =    0.0
A0   # num import send : avg = 1.53e+03,  dev =   7.5%,  min =  -18.7%,  max =  +10.3%
A0   # num msgs        : avg =     9.75,  dev =   1.47,  min =    6.0 ,  max =   13.0
A0   # min msg size    : avg = 2.66e+00,  dev = 163.5%,  min =  -62.4%,  max = +464.7%
A0   # max msg size    : avg = 2.60e+02,  dev =   2.9%,  min =   -1.5%,  max =  +11.1%
```

### 1024 cores
```
A0 size =  2113536 x 2113536, nnz = 15155200
A0 Load balancing info
A0   # active processes: 1024/1024
A0   # rows per proc   : avg = 2.06e+03,  dev =   4.9%,  min =  -13.2%,  max =  +18.6%
A0   #  nnz per proc   : avg = 1.48e+04,  dev =   7.9%,  min =  -15.2%,  max =  +31.4%
A0 Communication info
A0   # num export send : avg =     0.00,  dev =   0.00,  min =    0.0 ,  max =    0.0
A0   # num import send : avg = 1.04e+03,  dev =   5.9%,  min =  -17.4%,  max =  +12.2%
A0   # num msgs        : avg =     9.75,  dev =   1.08,  min =    6.0 ,  max =   13.0
A0   # min msg size    : avg = 1.45e+00,  dev =  94.6%,  min =  -31.2%,  max = +381.7%
A0   # max msg size    : avg = 2.58e+02,  dev =   2.1%,  min =   -0.8%,  max =   +5.4%
```

**Comment by aprokop** [comment]
The imbalance is actually quite severe on high core counts. If you look at the following line for 1024 cores
```
A0   #  nnz per proc   : avg = 1.48e+04,  dev =   7.9%,  min =  -15.2%,  max =  +31.4%
```
it means that there are two processor with one having 35% more rows and  54% more nonzeros than the other.

**Comment by jhux2** [comment]
It appears that the decomposition is controlled by IOSS (see ```Trilinos/packages/seacas/libraries/ioss/src/main/shell_interface.C```).  There are quite a few options there besides rcb, which is what was used for the stats I posted.

**Comment by jhux2** [comment]
I've tried different options for  ```automatic_decomposition_type``` for the 1024 core case.  Here are the results.  Note that ```rib``` gives a linear system imbalance in rows and nonzeros of 6% and 28%, respectively.

### 1024 core, ```rib``` decomposition
```
A0 size =  2113536 x 2113536, nnz = 15155200
A0 Load balancing info
A0   # active processes: 1024/1024
A0   # rows per proc   : avg = 2.06e+03,  dev =   2.1%,  min =   -0.8%,  max =   +5.4%
A0   #  nnz per proc   : avg = 1.48e+04,  dev =   8.6%,  min =   -4.0%,  max =  +22.8%
A0 Communication info
A0   # num export send : avg =     0.00,  dev =   0.00,  min =    0.0 ,  max =    0.0
A0   # num import send : avg = 1.04e+03,  dev =   5.1%,  min =  -12.0%,  max =   +2.7%
A0   # num msgs        : avg =     9.75,  dev =   1.56,  min =    6.0 ,  max =   12.0
A0   # min msg size    : avg = 2.88e+00,  dev = 172.6%,  min =  -65.2%,  max = +456.5%
A0   # max msg size    : avg = 2.58e+02,  dev =   2.1%,  min =   -0.8%,  max =   +5.4%
```
### 1024 case, ```hsfc``` decomposition
```
A0 size =  2113536 x 2113536, nnz = 15155200
A0 Load balancing info
A0   # active processes: 1024/1024
A0   # rows per proc   : avg = 2.06e+03,  dev =   8.0%,  min =  -18.6%,  max =  +18.6%
A0   #  nnz per proc   : avg = 1.48e+04,  dev =  11.5%,  min =  -20.5%,  max =  +58.1%
A0 Communication info
A0   # num export send : avg =     0.00,  dev =   0.00,  min =    0.0 ,  max =    0.0
A0   # num import send : avg = 1.04e+03,  dev =   9.2%,  min =  -29.0%,  max =  +23.1%
A0   # num msgs        : avg =    12.77,  dev =   3.67,  min =    6.0 ,  max =   25.0
A0   # min msg size    : avg = 6.40e+00,  dev = 137.3%,  min =  -84.4%,  max = +1776.3%
A0   # max msg size    : avg = 2.57e+02,  dev =   5.0%,  min =  -12.5%,  max =  +12.4%
```

Options ```cyclic```, ```block```, ```random```, and ```linear``` resulted in terrible load-balancing, so I don't include them here.

**Comment by aprokop** [comment]
@jhux2 Did you run `rib` to completion? If yes, how does it compare timing wise?

**Comment by mbarone81** [comment]
I am looking into the mesh decomposition for these cases.

**Comment by alanw0** [comment]
In the cases I've looked at in nalu, the element balance has been perfect, and the node balance is the issue. The node balance is what determines the linear system distribution. Currently stk-mesh doesn't do a great job of choosing processor-owners for the nodes that are shared by multiple procs (MPI ranks). The STK team has Karen Devine working on some improved load-balancing approaches that will hopefully make that better. I've tried some simple approaches to balancing the shared nodes, and it turns out to be non-trivial.

**Comment by mbarone81** [comment]
Wouldn't the node imbalance affect the momentum equation system as well?  We observed near-ideal strong scaling for the momentum solve.

**Comment by alanw0** [comment]
Yes I would have expected the momentum equation system to be affected just as much...

**Comment by mbarone81** [comment]
@jhux2, is it possible to extract number of rows and nnz for the momentum system as well in order to compare to the continuity linear system?

**Comment by aprokop** [comment]
@mbarone81 The statistics are currently coming from MueLu. I could port the code implementing it to Nalu's LinearSystem.C to use for momentum.

**Comment by jhux2** [comment]
> @jhux2 Did you run rib to completion? If yes, how does it compare timing wise?

I am rerunning with MueLu output completely off to get clean numbers.

**Comment by spdomin** [comment]
Nice discussion... In the end, it's what @alanw0 said in that the current rule for node ownership in STK is lowest rank. There have been a simple change in STK to make the local ownership be random in order to allow for a more balanced set of nodes, and, therefore, matrix rows. We also have real load balancing capability in STK, so we could try something like that.

Finally, the aura-based assembly may or may not help in this case. This would at least remove a "load_complete-like" step.

**Comment by jhux2** [comment]
```rib``` mesh decomposition yields a modest improvement in setup and solve performance at 512 cores, but none at 1024 cores.

![rcb-vs-rib](https://cloud.githubusercontent.com/assets/12970120/22954793/56139b98-f2cd-11e6-9f8f-e852352d4cc4.png)

**Comment by spdomin** [comment]
@jhux2, @rcknaus provided @mbarone81 a nodal load balance patch that has been used in our internal codes before. This patch removes the underlying rule of lower rank wins local nodal ownership. For hybrid meshes, this load balance is worse and was shown to do very well with re-balancing.

**Comment by mbarone81** [comment]
@jhux2, which mesh did you use for the results reported in this thread?

**Comment by jhux2** [comment]
> @jhux2, which mesh did you use for the results reported in this thread?

@mbarone81 All of the results in this thread are based on the mesh file  ```abl_3km_128.g```.

**Comment by mbarone81** [comment]
OK..I have the aforementioned node-balancing patch, with additional balancing info reported in the log file, integrated into Nalu. I will re-rerun some of the ABL cases and assess the effect this has on timings.

**Comment by spdomin** [comment]
Let's not forget that if this case is still using periodic bcs (double periodicity) then one of the opposing surfaces (for each periodic pair) will own the periodic rows. Moreover, corner nodes may also have more work on them due to the reconciliation of M/S pairs. 

Recall the simple one-D STK global ID:

`0-------1--------2--------3
`
and the mapping to NaluID - which is what the linear system sees:
`
0-------1-------2--------0`

I guess in the end, we should be looking at row/column map sizes for local and shared.

**Comment by spdomin** [comment]
Transition to Jira.
