### ISSUE TITLE
Periodic + DG/Overset in one simulation (assuming non-interacting nodes)

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#89]
dofStatus throws when periodic and overset/DG is active even though the nodes may not be painted with both types.

Allowing for a full pitching/plunging with DG/overset and periodic may be hard without a major refactor, however, we should take a look t see if dofStatus can be changed to support and ABL-like simulation with internal contact surfaces.

1. Evaluate dofStatus changes under the assumption that nodes are either periodic or DG/overset, however, not both.

2. Evaluate TpetraLinSys under many ghosting contributions. The code now may or may not support multiple ghosting.s I think it does, however, let's make sure.

3. take notes on what it would take to support a true pitching/plunging-like use case.

**Comment by spdomin** [comment]
I looked at this code today. It looks like to me that we can easily move forward in supporting this intermediate use case.

What is the required timeline for this fix?

**Comment by mbarone81** [comment]
Relative to the ABL testing with nested mesh, there are workarounds and so this fix is not on a critical path.

**Comment by spdomin** [comment]
@skennon10 and I sat down and both are on the same page wrt to the following push:

https://github.com/NaluCFD/Nalu/commit/e146fc4d73d7d96af174375dd86523a10e8f1825

This issue is now resolved; a test is being added soon.

**Comment by spdomin** [comment]
This issue was actually not resolved as a numberof Me469 students found this bug - despite the fact it was closed.

See:  

https://github.com/NaluCFD/Nalu/commit/f9ea67b5fe4dba99cb0035ea6d0babc68a792d7a

dofStatus is still plagued by bad naming. I think that our name cahnge way back when was overly simple and not correct. Specifically, we did need a notion richer than "sharedNotOwned"
